url = 'https://www.ebay.com'
browser = 'chrome'
categor = 'id:gh-shop-a'
computerTablet = '//div[@id="gh-sbc-o"]//a[text()= "Computers & tablets"]'
componentPart = '//li[@id="s0-16-12_2-0-1[0]-0-0-27[12]-0"]'
moboCpu = '//li[@id="s0-16-12_2-0-1[0]-0-0-27[12]-0"]//li[6]'
allFilter = '//button[@aria-label="All Filters"]'
filtByCpu = '//div/span[text()="CPU Series"]'
cbxProc = '//input[contains(@id, "20i7") and contains(@id, "2011th")]/..'
filtByMobo = '//span[text()="Motherboard Brand"]'
cbxMobo = '//input[contains(@id,"20Brand_ASRock_cbx")]/..'
appl = '//button[@aria-label="Apply"]'
checkFilt = '(//ul[@class="brm__list"]//span)[1]/..'
